/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import modelo.Jugador;
import modelo.TipoImagen;

/**
 *
 * @author El duro
 */
public class FormInicio extends javax.swing.JFrame {

    /**
     * Creates new form FormInicio
     */
    public FormInicio() {
        init();

    }

    public void init() {
        setUndecorated(true);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        panelFondo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panelFondo = new javax.swing.JPanel();
        cierre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtjugador = new javax.swing.JTextField();
        panelBoton = new javax.swing.JPanel();
        iniciar = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(14, 19, 49));
        panelFondo.setPreferredSize(new java.awt.Dimension(416, 315));
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFondoMousePressed(evt);
            }
        });
        panelFondo.setLayout(null);

        cierre.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        cierre.setForeground(new java.awt.Color(255, 255, 255));
        cierre.setText("X");
        cierre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cierreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cierreMouseExited(evt);
            }
        });
        panelFondo.add(cierre);
        cierre.setBounds(380, 10, 25, 20);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gato");
        panelFondo.add(jLabel1);
        jLabel1.setBounds(0, 30, 410, 50);

        txtjugador.setBackground(new java.awt.Color(214, 252, 249));
        txtjugador.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        txtjugador.setForeground(new java.awt.Color(101, 10, 245));
        txtjugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjugador.setText("JUGADOR");
        txtjugador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtjugadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtjugadorFocusLost(evt);
            }
        });
        txtjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjugadorActionPerformed(evt);
            }
        });
        txtjugador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjugadorKeyTyped(evt);
            }
        });
        panelFondo.add(txtjugador);
        txtjugador.setBounds(100, 100, 240, 50);

        panelBoton.setBackground(new java.awt.Color(42, 22, 79));
        panelBoton.setForeground(new java.awt.Color(42, 22, 79));

        iniciar.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        iniciar.setForeground(new java.awt.Color(241, 227, 252));
        iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciar.setText("INICIAR");
        iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iniciarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonLayout = new javax.swing.GroupLayout(panelBoton);
        panelBoton.setLayout(panelBotonLayout);
        panelBotonLayout.setHorizontalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        panelBotonLayout.setVerticalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelFondo.add(panelBoton);
        panelBoton.setBounds(140, 170, 160, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cierreMouseClicked

    private void cierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreMouseEntered
        cierre.setForeground(Color.RED);
    }//GEN-LAST:event_cierreMouseEntered

    private void cierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreMouseExited
        cierre.setForeground(Color.WHITE);
    }//GEN-LAST:event_cierreMouseExited

    private void txtjugadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtjugadorFocusGained
        if(txtjugador.getText().equals("JUGADOR")){
            txtjugador.setText("");
        }
    }//GEN-LAST:event_txtjugadorFocusGained

    private void txtjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjugadorActionPerformed

    private void txtjugadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtjugadorFocusLost
        if(txtjugador.getText().equals("")){
            txtjugador.setText("JUGADOR");
        }
    }//GEN-LAST:event_txtjugadorFocusLost

    private void panelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMousePressed
        panelFondo.requestFocus();
        
    }//GEN-LAST:event_panelFondoMousePressed

    private void txtjugadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjugadorKeyTyped
        char caracter = Character.toUpperCase( evt.getKeyChar());
        evt.setKeyChar(caracter);
        if(txtjugador.getText().length()>=8){
            evt.consume();
        }
        
        
        
    }//GEN-LAST:event_txtjugadorKeyTyped

    private void iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseEntered
        panelBoton.setBackground(new Color(126,49,196));
    }//GEN-LAST:event_iniciarMouseEntered

    private void iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseExited
        panelBoton.setBackground(new Color(42,22,79));
    }//GEN-LAST:event_iniciarMouseExited

    private void iniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMousePressed
        this.dispose();
        //Dificultad pantalla_dificultad = new Dificultad();
        //pantalla_dificultad.setVisible(true);
        Jugador jugador = new Jugador(TipoImagen.EQUIS);
        if(txtjugador.getText().equals("")){
            jugador.setNombre("JUGADOR1");
        }else{
            jugador.setNombre(txtjugador.getText());
        }
        Jugador maquina = new Jugador(TipoImagen.CIRCULO);
        maquina.setNombre("MAQUINA");
        
        
        FormGato gato = new FormGato(jugador, maquina);
        gato.setVisible(true);
    }//GEN-LAST:event_iniciarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cierre;
    private javax.swing.JLabel iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField txtjugador;
    // End of variables declaration//GEN-END:variables
}
