
package vista;

import java.awt.Color;
import modelo.Jugador;
import modelo.Tablero;

/**
 *
 * @author El Duro
 */
public class FormGato extends javax.swing.JFrame {
    private Jugador jugador1;
    private Jugador jugador2;
    private Tablero tablero;

    /**
     * Creates new form FormGato
     */
    public FormGato(Jugador jugador1, Jugador jugador2) {
        this.jugador1 = jugador1;
        this.jugador2 = jugador2;
        init();
    }
    public void init(){
        setUndecorated(true);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        jugador.setText(jugador1.getNombre());
        maquina.setText(jugador2.getNombre());
        
        tablero = new Tablero();
        tablero.setJugador(jugador1);
        tablero.setMaquina(jugador2);
        tablero.setAlturaCI(100);
        tablero.setAnchoCI(100);
        tablero.setMargen(5);
        tablero.setColorCI(new Color(14,19,43));
        tablero.setColorTablero(new Color(239,180,255));
        tablero.setLocation(40,150);
        tablero.crearTablero();
        tablero.setVisible(true);
        panelFondo.add(tablero);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        cierre = new javax.swing.JLabel();
        maquina = new javax.swing.JLabel();
        jugador = new javax.swing.JLabel();
        puntaje2 = new javax.swing.JLabel();
        puntaje1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(14, 19, 43));

        panelFondo.setBackground(new java.awt.Color(14, 19, 43));
        panelFondo.setPreferredSize(new java.awt.Dimension(400, 500));
        panelFondo.setLayout(null);

        cierre.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        cierre.setForeground(new java.awt.Color(255, 255, 255));
        cierre.setText("X");
        cierre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cierreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cierreMouseExited(evt);
            }
        });
        panelFondo.add(cierre);
        cierre.setBounds(360, 10, 25, 20);

        maquina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maquina.setForeground(new java.awt.Color(255, 200, 255));
        maquina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maquina.setText("NAME");
        panelFondo.add(maquina);
        maquina.setBounds(240, 70, 90, 30);

        jugador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jugador.setForeground(new java.awt.Color(180, 252, 255));
        jugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugador.setText("NAME");
        panelFondo.add(jugador);
        jugador.setBounds(60, 70, 90, 30);

        puntaje2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        puntaje2.setForeground(new java.awt.Color(255, 255, 255));
        puntaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje2.setText("0");
        panelFondo.add(puntaje2);
        puntaje2.setBounds(250, 20, 60, 60);

        puntaje1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        puntaje1.setForeground(new java.awt.Color(255, 255, 255));
        puntaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje1.setText("0");
        panelFondo.add(puntaje1);
        puntaje1.setBounds(80, 20, 60, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cierreMouseClicked

    private void cierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreMouseEntered
        cierre.setForeground(Color.RED);
    }//GEN-LAST:event_cierreMouseEntered

    private void cierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreMouseExited
        cierre.setForeground(Color.WHITE);
    }//GEN-LAST:event_cierreMouseExited

    public Jugador getJugador1() {
        return jugador1;
    }

    public void setJugador1(Jugador jugador1) {
        this.jugador1 = jugador1;
    }

    public Jugador getJugador2() {
        return jugador2;
    }

    public void setJugador2(Jugador jugador2) {
        this.jugador2 = jugador2;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cierre;
    private javax.swing.JLabel jugador;
    private javax.swing.JLabel maquina;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel puntaje1;
    private javax.swing.JLabel puntaje2;
    // End of variables declaration//GEN-END:variables
}
